### ISSUE TITLE
RFC; change backend from go to nodejs

### ISSUE THREAD

**Issue by jippi** [iverberk/nomad-ui#101]
Just a personal preference here, since i don't know Go at all :) 

Considering we already heavily use js for the frontend, it may be easier for new contributors to start out if the backend also is js rather than a 2nd language. 

Some of the ideas I have for the project I could easily implement in node, but won't be impossible for me to do in Go.

Considering the fairly simple backend, it should be somewhat easy to it to node - and since the project is shipped through docker, it should be a safe change to do there as well, as there would be no additional complexity for just consuming the project.

Additional upside is that the nodejs community got a stupid amount of cool packages that we could benefit from, and have similar non-block async behavior as Go.

**Comment by iverberk** [comment]
My personal preference is Go, because I don't know how to create a backend in Node :-)

Kidding aside, there is a big advantage to using Go and that is that we get to piggyback on the Nomad API package which will always be maintained and developed as part of Nomad. This way we don't have to bother with keeping in sync with API and just get to use all the good stuff. 

Backend work is definitely different from frontend work even if it is the same language and I think that Go is more suited to this particular task. Another aspect is that people are also just running the binary (with Nomad) and not relying on Docker. Using Go makes this trivial but Node would require a suitable runtime environment (on all platforms).

Like you said, the backend is fairly simple at this moment and Go has enough packages to provide flexibility when we need it. For now I would like to keep using Go. Please tell me what you want to achieve and we'll implement it :)

**Comment by themalkolm** [comment]
I agree that it is the best thing to distribute nomad-ui same as nomad itself i.e. via native binaries.

**Comment by jippi** [comment]
ok, I yield then :)
