### ISSUE TITLE
new #nomad-ui slack channel in Hangops

### ISSUE THREAD

**Issue by jippi** [iverberk/nomad-ui#102]
I've added a #nomad-ui room in the Hangops community on Slack ( https://signup.hangops.com/ ) 

There are already a huge number of people in #hashicorp and #docker channels, so seem like the right place to keep it around :)

**Comment by iverberk** [comment]
I'd rather we use Gitter if you don't mind. Nomad already has a room there and it seems a little bit more geared towards developers and structured around a project/repository. What do you think?

**Comment by jippi** [comment]
where is that gitter room? :) 

never used gitter before, and personal preference is that i (personally) would like to not have a 4th chat client for open source chatter. IRC, Twitter and Slack is already hard to keep up with :) 

Hangops is more or less the de facto community for tech stuff, and 700+ people in the hashicorp room is more or less our prime audience :)

**Comment by iverberk** [comment]
https://gitter.im/hashicorp-nomad/Lobby

I fully understand the desire not to have another app for communication. The compelling reason for me is the fact that HashiCorp has decided to use Gitter for Nomad and that the devs and users are there. It's specific to Nomad which would align nicely with this project :-)

I think/expect that HashiCorp will move more communications to Gitter in the future, but not sure. With Gitter I think we target the right audience and not get lost in the general Ops/HashiCorp talk about all their products. If you are ok with it I will create the room so that we can chat in real-time.

**Comment by jippi** [comment]
If it's Nomad's way of doing it, lets roll with it :)

**Comment by jippi** [comment]
@iverberk before moving it, would it make sense to move nomad-ui to a org to make it independent of one single person, since gitter also stick to username/repo ?
