### ISSUE TITLE
Release to DockerHub

### ISSUE THREAD

**Issue by jippi** [iverberk/nomad-ui#62]
Hi @iverberk 

When do you plan to ship the next image on dockerhub ? :)

**Comment by themalkolm** [comment]
It is easy to configure automatic builds on docker hub.

**Comment by iverberk** [comment]
I've configured the automated builds on the Docker hub. I'm now working on the github releases as they serve as input for the Docker build (linux-binary).

**Comment by jippi** [comment]
@iverberk how did it go with docker builds? i've been stalking during the day, and you've been jumping back and forth between auto-build and not - any issues?

**Comment by iverberk** [comment]
@jippi it didn't go a smoothly as I would have hoped. Instead of building separately with Docker Hub I just want Travis to push an image after a successful build. Maybe I didn't look enough into the Docker Hub builds but it makes more sense to me to just let Travis take care of it since we already have the binary at that point. 

I'm trying to get the following logic to work:

A new image will be pushed if master gets updated (with tag latest) or if a tag is pushed. A github release will be created when a tag is pushed. Trying to make it work on travis right now, but will take some trial-and-error and don't have much time tonight. I'll try to get it done as quickly as possible.

**Comment by iverberk** [comment]
We're getting somewhere now. Just needs a little fine-tuning but I've got to go now. I'll try to look at it later tonight.

**Comment by themalkolm** [comment]
Do we really plan to build & upload release for every commit on master?

**Comment by iverberk** [comment]
No, but I didn't have enough time yesterday to make it nice :-) Will fix tonight. I was hoping that I could publish a 'latest' release to github and tag to Docker hub that gets updated with every new commit to master so that people can try the latest version easily, but it shouldn't generate new releases, it should just overwrite the previous one. With tags we would create a nice tagged release. Do you have other ideas about this?

**Comment by jippi** [comment]
@iverberk not sure if things are supposed to work yet, but `docker run -e NOMAD_ADDR=xxxx -e NOMAD_PORT=4646 -p 8000:3000 iverberk/nomad-ui:latest` (pulled 5min ago) simply outputs `standard_init_linux.go:175: exec user process caused "no such file or directory"`

**Comment by iverberk** [comment]
@jippi yeah, I noticed just now. Not sure what's going yet. If I build the Docker image on my local machine it works just fine. Apparently something is different on the Travis environment, not sure what though. Will investigate now.

**Comment by iverberk** [comment]
@jippi should be all good now. Travis wasn't producing a static binary. I'm going to close this! :-)
