### ISSUE TITLE
refresh loads no data on all pages

### ISSUE THREAD

**Issue by jippi** [iverberk/nomad-ui#89]
Hi

Navigating to `http://localhost:8000/#/members/5b3a8a63-3a12-d0b1-2668-9407e94374b2/info?_k=tbi8os` and refreshing the page yields no data / node info 

If i navigate to the page again from the menu, it works fine

This seem to be for all non-index / list pages 

The server log outputs

`11:01:04.241 connection.go:49 ▶ ERRO  Could not write close message to websocket: websocket: close sent`

I'm running `iverberk/nomad-ui:latest` on nomad 0.4.1

**Comment by themalkolm** [comment]
Yep, almost every page is broken in this way. This is due the fact that on complete refresh/fresh load it requests information (watches) before websocket connection is even established. This effectively makes page believe that has requested information while actually nothing happened.

The reason it works for list pages is because there is internal caching for them on backend side.

**Comment by jippi** [comment]
okay, any workaround / fix for this ? :)

**Comment by jippi** [comment]
@themalkolm did you continue working on your fork somewhere? I'm currently switching from supervisor to nomad, and would be nice with a nomad-ui that is somewhat functional for basics, and you seemed to have a good pace when you participated in the repo

**Comment by themalkolm** [comment]
The workaround is to always navigate from the index page.

**Comment by themalkolm** [comment]
@jippi yes, I keep working on it. I can't share it but I can share our experience and issues you are guaranteed to face e.g. try to schedule 1000 jobs and try to make sense of what is going on in the cluster using this ui :) It will also likely to simply die due exceeding number of objects.

**Comment by iverberk** [comment]
@jippi I will fix this problem for you, are there any other concerns that you have that need attention? This really helps me in prioritizing issues.

@themalkolm if you have the luxury of working on this at your day job why don't you make a public repo so that we can all contribute back to that and then you can maintain it and deal with the issues/PR's, instead of telling people what is wrong with this project? It took a lot effort on my part, in my free-time, to get this off the ground and while you've made useful contributions the core was already there. If you are not putting proprietary stuff in the UI then why can't it be open-sourced?

If people are going to use this at massive scale then yeah, there will be probably be issues with the UI. Since I have not heard about these issues it is not a priority for me. If your are going to schedule thousands or millions of jobs then this UI, or maybe any UI for that matter, is not going to work out real well but with a little help from the community this can be fixed, or you can use (and pay for) HashiCorp's offering once it is released :-)

**Comment by themalkolm** [comment]
@iverberk I thought it is obvious. I can't share my code as it belongs to the company. What is wrong with me pointing out potential problems a future user will face?

**Comment by themalkolm** [comment]
So, instead of being frustrated @jippi now at least know that there is somebody who probably has answers / ideas to common problems due actually using this project in production. I see this as a _good_ thing.

**Comment by iverberk** [comment]
Ok, reading back on your reactions I might have overreacted as you are simply stating the case. There's nothing wrong with it and I agree that it is a good thing that you are telling about your experiences in production use, as I'm not using it in production myself. Maybe you can share those experiences in the form of issues that you've encountered (not necessarily PR's) so that other people who are evaluating the project can make a proper judgement for their use-case. I guess I'm just a little bummed that I can't spend enough time on it and you can :-)

**Comment by themalkolm** [comment]
@iverberk no hard feelings. 

We do consider sharing back our experience but we are still in the pre-alpha stage for our project.. We are rushing though and constantly changing things all around.

While I can help explain current bugs or limitations, I don't have 100% certainty in our approach as we are yet to release it to our internal customer and see it in action for long run.

**Comment by jippi** [comment]
@iverberk do you plan to run this project yourself in production level environment anytime soon ? 

Having a project owner that doesn't use the project in production himself could be poential danger zone (abdondon project / not every-day user / lack of spare-time to work on it / not equally suffering from pain points in the usage) 

I haven't observed any of these issues yet for nomad-ui though! if nothing else it would be lovely to know if you plan to roll it somewhere critical yourself too :)

**Comment by dropje86** [comment]
Just for the sake of it. We're also currently ramping up our Nomad deployment and expect to run all of our services dockerized and scheduled by Nomad within 6 months. One of the biggest downsides so far is that Hashicorps Atlas will not be deployed in our company due to both technical constraints (AWS only support so far) and the maturity of the product in general. For now we're happy customers of this project because it does give you the opportunity to get some simple feedback on Nomads status (logs like mentioned in another issue are a problem though, not too bad for us as we're logging to Kafka -> Elastic)

My Node/JavaScript knowledge is very limited (non-existent) as I'm an OPS guy and it never interested me enough to start learning. I will try to get some traction internally from our frontenders to get a bit of commitment on this project. Hopefully that'll happen automagically when ppl have to work with the ui on a frequent basis.

**Comment by iverberk** [comment]
@jippi I'm probably not going to run it in a production environment any time soon. At my current client they are not using Nomad unfortunately and personally I don't have a use-case running it in production. I understand your concern and I would also rather see that I can evolve the project based on actual working hours and production usage but alas...

This is the blessing and curse of doing open-source work. I think most people (probably not companies) start open-source projects for fun, learning and problem solving. Once it becomes successful and people start depending on it for the day-to-day work, the expectations change. Depending on the maintainer's resources (s)he might or might not be able to live up to the expectations. What to do?

There are no guarantees to be had (it's free after all) but since it's open-source you can always fork and maintain/evolve it yourself. You'll have to make a judgement call if you want to go this route if things go bad. I think in the ideal case, multiple people/companies contribute to the project and it won't depend on a single person anymore. I'd be more than happy to go that route if I think the project has a stable core and that there are enough contributors/committers that can discuss and evolve the project in a future-proof way. Right now it's just me and a lot of useful contributions by @themalkolm. Unfortunately he is not able to share his further improvements but we can benefit from his experiences and he seems committed to the project.

Let me finish off by saying that I have no intention of abandoning this project but I am limited in the time that I can spend on it. Things will sometimes move slowly sometimes because of it. Nomad definitely seems to be picking up pace and the lack of a proper UI by HashiCorp will only strengthen interest in the project I think. Hopefully, with the help of the community, we can quickly come to a situation where people that use it in production become active contributors and/or committers. Maybe this is more of an observation than an answer but I hope it helps any way!

**Comment by iverberk** [comment]
Fixed by @jippi in #100
