### ISSUE TITLE
short/long term project goals

### ISSUE THREAD

**Issue by jippi** [iverberk/nomad-ui#90]
@iverberk thanks for a great project

could you share your thoughts on short and maybe long term goals you want to work on?

I'm currently moving our infrastructure from supervisor to nomad, and a UI is essential for that being a successful migration.

We do have some react resources at bownty, so we should be able to give something back (ala what @themalkolm did back in the beginning) to help move the project forward.

Thinks I feel is missing atm are an easy way to get an overview of errors happening in the cluster.

examples:

- list over failed `allocations`, `evaluations` and most importantly, `jobs`
- sortable columns in index / lists (e.g. on `status` column in jobs) 
- simple freetext search on index / list pages (on name / type)

**Comment by iverberk** [comment]
@jippi this is really helpful. I will try to come up with an answer shortly!

**Comment by iverberk** [comment]
@jippi thanks for your thoughts.

So I fully intend for this project to give you all the necessary information/overviews to manage a big Nomad cluster. This means full insight in the data structures, state, stats and messages. Marathon, Kubernetes etc. all have a UI to get a quick overview of the state of the cluster and I hope this project will do the same for Nomad.

Since I'm unfortunately not running Nomad in production myself, my intention was to listen what people had to say about it and prioritize from there. Slowly but surely people like yourself are running up against the limits of what the app can do right now. By creating issues, I and other interested parties will be able to understand where the most urgent problems are and start fixing them.

The only way to speed things up is if people start contributing to the project. Hopefully this will happen when people commit to the project for their daily usage. Your examples are all valid requests that should be addressed.

So long term goals would be to visualize all the stuff that Nomad's API is able to deliver but also to intelligently show the most urgent issues with the cluster first (like failures, resource usage, etc.) and not just be a "dumb" dashboard. Giving feedback on what you consider essential information that should be on the landing page will give a big boost to making Nomad UI all the more useful. Right now, it's just what I could come up with but it is by no means the only way.

Short term goals would be like your examples to improve the UI with basics. File/log downloads should be supported, big logs should not fill up the browser, thousands of jobs should not overwhelm the UI and other relatively low-hanging fruit. Stuff like that would be for the short-term in my opinion.

If having a Nomad UI is essential for having a successful migration please consider very carefully what your alternative scenario's are in case this project in one way or another does not live up to the expectations. I'm confident that we can evolve this to what it needs to be, but I'm not sure how fast. Let's start improving it together now! :-D I will create separate issues for your examples to better manage them.

**Comment by iverberk** [comment]
I'm going to close this. We'll create issues/milestones to lay out the roadmap.
